site_name: 顶誉律师行 - 移民资讯网
site_url: https://jadeimmigration.netlify.app/
copyright: 版权所有 &copy; 2023 顶誉律师行

# local serve to a different portal:
# mkdocs serve -a localhost:8001

nav:
  - 新闻早知道:
      - blog/index.md
  - 联邦项目:
      - 联邦SUV项目: fed/suv-bundle.md
  - 阿省提名项目:
      - 投资移民:
          - 小镇投资移民:
              - 项目介绍: RES/intro.md
              - 入门条件: RES/grid.md
              - 投资承诺协议: RES/bpa.md
              - 买卖生意注意事项: RES/2024-12-19-bizPurchase.md
              - 小镇简介: RES/communities.md
          - 毕业生创业移民: FGES/intro.md
      - 技术移民:
          - 普通项目:
              - 项目介绍: AOS/intro.md
              - 合格申请人条件: AOS/eligibility.md
          - EE项目:
              - 项目介绍: AEE/intro.md
              - 资格条件: AEE/eligibility.md
          - 乡村振兴项目:
              - 项目介绍: RRS/intro.md
              - 资格条件: RRS/conditions.md
              - 乡村小镇简介: RRS/communities.md
  - NS省提名项目:
      - 投资移民: NovaScotia/businessStream.md
  - 安省提名项目:
      - 安省硕博通道: Ontario/master.md
  - 临时签证类:
      - 旅游签:
          - 停留期限及续期办法: temporary/vve.md
          - 官方释义及要求: blog/posts/2024-06-24-someDefinition.md
      - 工签:
          - 工签到期的处理: temporary/wp-expire.md
          - 留学生校外打工: temporary/offcampus.md
          - 边境工签的法律依据: temporary/WP-POE.md
          - 配偶担保工签: temporary/SOWP.md
  - 专栏文章精选:
      - 配偶团聚移民申请和上诉: articles/spouse-sponsor.md
      - LMIA申请流程和注意事项: articles/lmia.md
      - 海牙送达公约在国内的适用: articles/HagueService.md
      - PR持有人的居留义务: articles/RO.md
      - CLB 级别与语言考试成绩对照表: articles/clb-chart.md
  - 关于我们:
      - 本所介绍: index.md
      - 免责声明: about/disclaimer.md

theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: zh

  logo: jade_logo.png
  favicon: jade_logo.png

  features:
    - navigation.tabs
    - navigation.instant # without fully reloading the page, fast loading function
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.prune
    - navigation.footer
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy
    # - navigation.indexes ##enable it if you have an introduction to top level
    # - navigation.sections

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@jadesunriselawab
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/kathyzhq?mibextid=LQQJ4d
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/p/CyjGMfDhamf/
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@jadesunriselaw.com
  generator: false

plugins:
  - search
  - tags
  - blog:
      draft_on_serve: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/styled-table.css
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - assets/css/coverpic.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
  - assets/css/icon.css
  - assets/css/other.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
